title: Baby's First GitHub Page
author: ohrice
email: ericmho@ucla.edu
description: > # this means to ignore newlines until "baseurl:"
  This is my first GitHub Page. Please be gentle.
  
theme: minima

# social links
twitter_username: ohrice2
github_username:  ohrice

show_excerpts: true # set to false to remove excerpts on the homepage
